name: macOS Release Tracker

on:
  schedule:
    - cron: '19 * * * *'
  workflow_dispatch:

jobs:
  check-macos-releases:
    runs-on: ubuntu-latest
    env:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/macos-release-tracker/requirements.txt

      - name: Run script
        run: |
          python .github/workflows/macos-release-tracker/runner.py
